### PR TITLE
#972: Strategy for generating nodeId and nodePrivateKey

### LINKED ISSUE #972: Strategy interface for getGeneratedNodePrivateKey()
There is a TODO on the test `testGeneratedNodePrivateKeyThroughECKey` on the class `SystemPropertiesTest` to create a strategy interface for getGeneratedNodePrivateKey().

```
/**
 * TODO: Consider using a strategy interface for #getGeneratedNodePrivateKey().
 * Anything 'File' and 'random' generation are difficult to test and assert
 */
@Test
public void testGeneratedNodePrivateKeyThroughECKey() throws Exception {
    ...
}
```

I'd love to get someone to review my PR and come with suggestions for improvements.

### PR DESCRIPTION
**Pull request by lucassaldanha**
Fixes #972

### CODE REVIEW

**Comment by zilm13** [comment]
@lucassaldanha I'd prefer direct way to set fallback strategy in `GenerateNodeIdFromPropsFile` and change its name to `GetNodeIdFromPropsFile`. You will need to pass databaseDir 2 times in `SystemProperties` on init but it will not look like a hidden magic. Everything else looks great!
@mkalinin what do you think?

**Comment by zilm13** [comment]
So it will look this way in SystemProperties:
```
this.generateNodeIdStrategy = new GetNodeIdFromPropsFile(databaseDir()).withFallback(new GenerateNodeIdRandomly(databaseDir()));
```

**Comment by lucassaldanha** [comment]
> I'd prefer direct way to set fallback strategy in GenerateNodeIdFromPropsFile

@zilm13 Sure! Do you want the fallback to be optional? e.g. If one doesn't specify the fallback, what should happen? Thrown an error?

**Comment by zilm13** [comment]
@lucassaldanha yeah I think exception is better than null, so we get something wrong immediately if we have bad initialization. And you should be able to pass any `GenerateNodeIdStrategy ` in fallback.

**Comment by zilm13** [comment]
@lucassaldanha Looks good, thanks

**Pull request merged**
