### PR TITLE
Net refactoring and dependency cleaning.

### PR DESCRIPTION
**Pull request by adrian-tiberius**
### Review of changes:

- cleaned some dependencies;
- moved common functionality to extendable base classes for channels and protocol handlers;
- added listeners to protocol handlers, message codec, channel manager and syncQueue to reduce coupling between components;

**Account** - replace WorldManager dependency with Repository
**Wallet** - remove unused WorldManager dependency
**MessageQueue** - replaced WorldManager dependency with EtherumListener
**PeerClient** - replaced WorldManager dependency with EthereumListener
**NodeManager** - replaced WorldManager dependency with EthereumListener
**UDPListener** - removed unused WorldManager dependency
**PeerServer** - removed unused ChannelManager dependency and replaced WorldManager dependency with EthereumListener
**Hive** - added WorldManager dependency
**NetStore** - removed unused WorldManager dependency
**PeersPool** - replaced Ethereum dependency with ApplicationCotext for PeerClient use
**SyncQueue** - removed SyncManager dependency and added single event listener implemented in SyncManager
**ChannelManager** - removed unused WorldManager, NodeManager, Ethereum dependencies and replaced SyncManager dependency with a single event listener
**SyncManager** - implements ChannelManager and SyncQueue event listeners
**EthereumChannelInitializer** - removed unused WorldManager dependency

**MessageCodec** - replaced WorldManager dependency with EthereumListener, added single event listener, refactored getCode and createMessage methods;

#### Protocol handlers:
- moved base functionality in extendable ProtocolHandler class;
- added event listeners to protocol handlers;

**P2PHandler** - replaced WorldManager dependency with EthereumListener; added MessageQueue, ShhHandler, BzzHandler, EthHandlerFactory, PeerDiscovery dependencies and now extends ProtocolHandler class
**BzzHandler** - replaced WorldManager dependency with EthereumListener and now extends ProtocolHandler class
**ShhHandler** - replaced WorldManager dependency with EthereumListener and now extends ProtocolHandler class
**EthHandler** - replaced WorldManager dependency with EthereumListener and Wallet

#### Channels:
- moved common functionality to extendable ChannelBase class;
- removed MessageQueue, ShhHandler, BzzHandler, EthHandlerFactory dependencies(moved to P2PHandler) and added EthereumListener dependency;
- added InitiateHandler (moved from MessageCodec);
- implements MessageCodecListener and ProtocolHandlerListener event listeners;

### CODE REVIEW

**Comment by romanman** [comment]
@adrian-tiberius, thank you
 we will test your work and 
pull it In soon

**Comment by Nashatyrev** [comment]
Hi @adrian-tiberius,
thanks for your participation, we are glad to see the interest in contributions 

The `Cleaned unused deps` commit looks fine for me. 
The `Net refactoring` concepts basically looks fine however I have some major concerns: 

- Generally the commit should be split onto a smaller fine grained pieces - small commits are easier to review. The smaller the commit the better chance to test and accept it. 
- We have a number of internal projects which uses EthereumJ and it's internal classes so all the refactorings need to be made carefully not to break the working things 
- The `net.peerdescovery` package is basically deprecated and needs to removed, so there is no need to extract ChannelBase for now
- The `net.rlpx` classes were refactored heavily in the `rlpx-framing` branch which is to be merged to `stage` soon, so there are many conflicts arise 
- Finally the main test the changes should pass is the `gradlew run` - it should successfully import all the existing blocks. The current PR just breaks with NPE, though I don't think there is something serious.
Anton.

**Comment by adrian-tiberius** [comment]
Hi @Nashatyrev, thanks for your feedback. I will keep that in mind for future pull requests.

**Comment by romanman** [comment]
@adrian-tiberius :: what is plan regarding the 
awesome work you have  done?  My suggest 
it to split it to a autonomous PR.

**Comment by adrian-tiberius** [comment]
@romanman I will split the non-rlpx related changes into smaller commits adding pull requests for each, and will revisit the rlpx related changes after the rlpx-framing branch merge.

**Comment by romanman** [comment]
@Nashatyrev  @andrian-tiberius good strategy , 
thanks for flying ethereumJ

**Pull request closed without merging**
