### PR TITLE
#946 - Fixes for small configuration bugs found by tests

### PR DESCRIPTION
**Pull request by weisheme**
Could you please confirm that my reasoning is correct and that my bug fix is what you expected?

1. No longer accept nodes where the hostname cannot be resolved through `InetAddress.getByName()` **even** when
a `hostIpPattern = null` (wildcard) was provided.
1. Now accepts any InetAddress when `hostIpPattern = null` (wildcard) 
1. Only accept provided privateKey when it's Hex encoded

### CODE REVIEW

**Comment by mkalinin** [comment]
Should resolve https://github.com/ethereum/ethereumj/issues/963

**Comment by mkalinin** [comment]
@Nashatyrev please, take a look

**Comment by Nashatyrev** [comment]
Sounds reasonable

**Comment by mkalinin** [comment]
@weisheme could you pls stick your branch with `develop`?

**Pull request merged**
