### PR TITLE
Making DataWord class immutable

### PR DESCRIPTION
**Pull request by arsalankhalid**
PR for making DataWord class Immutable as per #706

### CODE REVIEW

**Comment by arsalankhalid** [comment]
@Nashatyrev Can I get a review please?

**Comment by arsalankhalid** [comment]
@humphd

**Comment by vetler** [comment]
DataWord is still mutable - methods change the internal byte array representation.
To be truly immutable, the internal representation would not change when calling methods like `and`, `add`, and so on.

**Comment by zilm13** [comment]
Resolved with #1154

**Pull request closed without merging**
