### PR TITLE
Update gradle command

### PR DESCRIPTION
**Pull request by ashishb**
Replace compile with implementation as recommended here:
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

### CODE REVIEW

**Comment by mkalinin** [comment]
This change makes sense in case if we use `java-library` plugin

**Comment by ashishb** [comment]
What's the plan to use that? Afaik, "compile" is [deprecated](https://stackoverflow.com/questions/44231886/android-gradle-4-0-compile-dependency-deprecated-how-does-new-api-configuration) in Gradle.

**Comment by mkalinin** [comment]
You know, maybe I was too fast with the decision.

**Comment by mkalinin** [comment]
Thx 👍

**Pull request merged**
