### PR TITLE
Refactor [#640]: Move Memory, Stack, Storage and ProgramTrace out of core

### LINKED ISSUE #640: Move Memory, Stack and Storage out of core
Make usage of Memory, Stack, Storage, ProgramTrace optional.
Refactor to use ProgramTrace only via callback. Remove trace specific options from core (like compression).

### PR DESCRIPTION
**Pull request by 95jonpet**
This should close #640.

Interfaces have been extracted from "Memory", "Stack", "Storage" and "ProgramTrace". Old implementations have been renamed to "DefaultMemory", "DefaultStack" etc. Null implementations following the null object pattern have been implemented as "NullMemory", "NullStack" etc.

New cli options (also available through the option --help):

--nomemory     Run without memory
--nostack          Run without stack
--nostorage      Run without storage
--notrace          Run without program trace

Code coverage has been increased and new unit tests have been added for the created classes.

Unused fields have been left untouched by this refactor as it is focused on making things more modular, and not general code cleanup.

### CODE REVIEW

**Comment by RichardH92** [comment]
This PR seems like really great work. Is it abandoned and/or is there a reason it was not merged?

**Comment by 95jonpet** [comment]
I can check it again to make sure it merges well with the other things that have happened in the project.

**Comment by mkalinin** [comment]
@95jonpet yep, that would be great

**Comment by 95jonpet** [comment]
The merge seems to work now.

**Pull request closed without merging**
