### PR TITLE
ADD SendTransaction sample

### PR DESCRIPTION
**Pull request by a7ex12**
I just simplified CreateContractSample for more clarity how to send transaction

### CODE REVIEW

**Comment by Nashatyrev** [comment]
Thanks!

**Comment by Nashatyrev** [comment]
Hey @a7ex12, if you have time can you take a look on issue with your sample please https://github.com/ethereum/ethereumj/issues/499 ? 
Thanks!

**Comment by a7ex12** [comment]
Hi Anton. I see the problem and made some changes to solve it, but need to
sync blockchain to check everything is fine. I'm at 2204000 and sync is
extremely slow.

9 сент. 2016 г. 19:33 пользователь "Anton Nashatyrev" <
notifications@github.com> написал:

**Comment by Nashatyrev** [comment]
If you switched to `1.3.0` release (or latest develop) you'd better sync from scratch. With old db it is really slow. 
BTW, just noticed you are using the main net for the sample. I would suggest to derive from the `TestNetSample` instead of `BasicSample`. It will 1) allow you to sign tx with existing test account with ethers, 2) full sync on the testnet is 10x times faster

**Comment by a7ex12** [comment]
Fix #499 with #502 
I got sync faster by my spring boot app based on ethereumj latest release.
It was interesting for me to see how it works in live Ethereum network, that's why i did it this way, but yes, it takes Tx Cost for every transaction, so yes, i think for experimenting with a lot of transactions it's better to derive from TestNetSample.

**Comment by cheershendtco** [comment]
Hi, I replace `BasicSample` keyword to `TestNetSample` 
(there are 2 BasicSample at line 24 and line 111)
ethereumj/ethereumj-core/src/main/java/org/ethereum/samples/SendTransaction.java
and I run 
`./gradlew runMorden -PmainClass=org.ethereum.samples.SendTransaction  --stacktrace --info  --debug > ~/log.txt
`
and I got BUILD FAILED
[log.txt](https://github.com/ethereum/ethereumj/files/489090/log.txt)

**Comment by a7ex12** [comment]
I dont have testNet and morden synced ,so cant check now, but pls try following changes:
- for testNet:
```
-public class SendTransaction extends TestNetSample
```
In void main:
```
class Config extends TestNetConfig {
            @Bean
            public TestNetSample sampleBean() {
                return new SendTransaction();
            }
        }
```

- for Morden:
```
-public class SendTransaction extends MordenSample
```
In void main:
```
class Config extends MordenSampleConfig {
            @Bean
            public MordenSample sampleBean() {
                return new SendTransaction();
            }
        }
```

**Comment by cheershendtco** [comment]
Hi i use ur `for testNet:` solution and now My Blockchain sync in same progress for either 
./gradlew runMorden or ./gradlew run
now I got this error
please help thanks
```
16:34:36.834 INFO [sample]  New block: #1663967 (24d886 <~ 907bd1) Txs:0, Unc: 0
16:34:38.393 ERROR [sample]  Error occurred in Sample: 
java.lang.RuntimeException: The transaction was not included during last 16 blocks: 7c92c02c
        at org.ethereum.samples.SendTransaction.waitForTx(SendTransaction.java:92)
        at org.ethereum.samples.SendTransaction.sendTxAndWait(SendTransaction.java:76)
        at org.ethereum.samples.SendTransaction.onSyncDone(SendTransaction.java:42)
        at org.ethereum.samples.BasicSample.run(BasicSample.java:141)
        at java.lang.Thread.run(Thread.java:745)
16:34:38.393 ERROR [sample]  Error occurred in Sample: 
java.lang.RuntimeException: The transaction was not included during last 16 blocks: 7c92c02c
        at org.ethereum.samples.SendTransaction.waitForTx(SendTransaction.java:92)
        at org.ethereum.samples.SendTransaction.sendTxAndWait(SendTransaction.java:76)
        at org.ethereum.samples.SendTransaction.onSyncDone(SendTransaction.java:42)
        at org.ethereum.samples.BasicSample.run(BasicSample.java:141)
        at java.lang.Thread.run(Thread.java:745)
16:34:40.430 INFO [sample]  New block: #1663968 (e0b56a <~ 24d886) Txs:0, Unc: 0

```

**Comment by a7ex12** [comment]
I'm syncing Morden to check it. BTW, did you try to check it on live network? (Be sure to have enouth wei to pay transaction fee).
Also can you pls post content of "<=== Sending transaction:..." line rfom you logs

**Comment by cheershendtco** [comment]
i am a very beginner . what is `live network` ? mainnet or Morden
is testnet equal to morden?

`"<=== Sending transaction:..." line ` do u mean this
```
16:22:58.309 INFO [sample]  <=== Sending transaction: TransactionData [hash=  nonce=00, gasPrice=104c533c00, gas=030d40, receiveAddress=, value=01, data=, signatureV=28, signatureR=ae0a4531ed12f787d3145eca1e519979000419f4f5b29036e1be5516df578604, signatureS=2008dd7d137b2680fd08430ebb31ae21708a2ec1ad30cc888d25b0c16bd8d06a]
16:22:58.358 INFO [sample]  Waiting for block with transaction 0x7c92c02c included (0 blocks received so far) ...
16:23:16.998 INFO [sample]  New block: #1663951 (45028f <~ fead05) Txs:0, Unc: 0
/*cut some line not relate to my question*/
16:33:38.390 INFO [sample]  Waiting for block with transaction 0x7c92c02c included (14 blocks received so far) ...
16:33:58.391 INFO [sample]  Waiting for block with transaction 0x7c92c02c included (14 blocks received so far) ...
16:34:08.542 INFO [sample]  New block: #1663965 (6854d6 <~ f0ec7e) Txs:0, Unc: 0
16:34:18.392 INFO [sample]  Waiting for block with transaction 0x7c92c02c included (15 blocks received so far) ...
16:34:32.169 INFO [sample]  New block: #1663966 (907bd1 <~ 6854d6) Txs:0, Unc: 0
16:34:36.834 INFO [sample]  New block: #1663967 (24d886 <~ 907bd1) Txs:0, Unc: 0
16:34:38.393 ERROR [sample]  Error occurred in Sample: 
java.lang.RuntimeException: The transaction was not included during last 16 blocks: 7c92c02c
        at org.ethereum.samples.SendTransaction.waitForTx(SendTransaction.java:92)
        at org.ethereum.samples.SendTransaction.sendTxAndWait(SendTransaction.java:76)
        at org.ethereum.samples.SendTransaction.onSyncDone(SendTransaction.java:42)
        at org.ethereum.samples.BasicSample.run(BasicSample.java:141)
        at java.lang.Thread.run(Thread.java:745)
16:34:38.393 ERROR [sample]  Error occurred in Sample: 
java.lang.RuntimeException: The transaction was not included during last 16 blocks: 7c92c02c
        at org.ethereum.samples.SendTransaction.waitForTx(SendTransaction.java:92)
        at org.ethereum.samples.SendTransaction.sendTxAndWait(SendTransaction.java:76)
        at org.ethereum.samples.SendTransaction.onSyncDone(SendTransaction.java:42)
        at org.ethereum.samples.BasicSample.run(BasicSample.java:141)
        at java.lang.Thread.run(Thread.java:745)

```
Thanks a lot

**Comment by a7ex12** [comment]
You don't have receiveAddress

**Comment by cheershendtco** [comment]
HI thanks . after I fill the 
toAddress and senderPrivateKey
I got this INFO

`18:16:36.947 INFO [sample]  <=== Sending transaction: TransactionData [hash=  nonce=00, gasPrice=104c533c00, gas=030d40, receiveAddress=66e536a4b3f5660ff0f38e21b33467dceb5ef88e, value=01, data=, signatureV=27, signatureR=916a26a2827ea860c6495115d7e69e26957cef6b77fbae3994ff2bd2d01baa10, signatureS=1a312553350403445f99ff564f7b85b5aa1c0ad7846393528cdfc5f548d0e997]
`
but when I check with 
https://testnet.etherscan.io/address/0x66e536a4b3f5660ff0f38e21b33467dceb5ef88e

there is no new transaction.


my last block is 
` New block: #1664165 (c35759 <~ 7e03f4) Txs:0, Unc: 0`
how do i know i complete my sync?

Did I miss something?Thanks.

**Comment by a7ex12** [comment]
Just sent transaction in Morden, see, everything works:
````
09:54:39.764 INFO [sample]  Waiting for the whole blockchain sync (will take up to several hours for the whole chain)...
09:54:49.764 INFO [sample]  Blockchain sync in progress. Last imported block: #1686735 (cbad2c <~ 09da3b) Txs:26, Unc: 0 (Total: txs: 286, gas: 6917k)
09:54:59.764 INFO [sample]  [v] Sync complete! The best block: #1686741 (a58e0b <~ 03690a) Txs:67, Unc: 0
09:54:59.765 INFO [sample]  Sending transaction to net and waiting for inclusion
09:54:59.770 INFO [sample]  <=== Sending transaction: TransactionData [hash=  nonce=1024a0, gasPrice=104c533c00, gas=030d40, receiveAddress=9bac8b2e2a310ef3d4e7993e982a886f3dc69dc8, value=01, data=, signatureV=28, signatureR=dba6c07fda0e3c938a1c8b94a98006699336f1a4e6b8ae1b2e16221cec55425e, signatureS=33b8cf8f42e033a2535c0b1021a644b6f6c3ba38855bfbcd185566fac9a13790]
09:54:59.805 INFO [sample]  Waiting for block with transaction 0xc5cf6969 included (0 blocks received so far) ...
09:55:19.805 INFO [sample]  Waiting for block with transaction 0xc5cf6969 included (0 blocks received so far) ...
09:55:32.325 INFO [sample]  New block: #1686742 (635d30 <~ a58e0b) Txs:2, Unc: 0
09:55:37.689 INFO [sample]  New block: #1686743 (c047fb <~ 635d30) Txs:11, Unc: 0
09:55:37.689 INFO [sample]  Transaction included!
09:55:51.523 INFO [sample]  New block: #1686744 (3aadee <~ c047fb) Txs:64, Unc: 0
````

Pls check again you made correct changes, for Morden for example there are 3 differences:
````
-public class SendTransaction extends MordenSample
-class Config extends MordenSampleConfig{
-public MordenSample sampleBean() {
```

**Comment by cheershendtco** [comment]
@a7ex12 Thank you for your time.
I am apologize that I ask basic question.

I modify for Morden and I get
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
:ethereumj-core:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ethereumj-core:run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-i386/bin/java'' finished with non-zero exit value 134

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```
this failed is not exist if I use 
```
public class SendTransaction extends TestNetSample {
class Config extends TestNetConfig {
public TestNetSample sampleBean() {
```

the result seems same either I use 
./gradlew runMorden -PmainClass=org.ethereum.samples.SendTransaction 
or
./gradlew run -PmainClass=org.ethereum.samples.SendTransaction 


here is my modified code below.
please see
line 25
line 134~139
Thanks a lot.
https://github.com/cheershendtco/ethereumj_test/blob/master/SendTransaction.java

**Comment by cheershendtco** [comment]
`byte[] senderPrivateKey = Hex.decode("");`
should I fill this privateKey with  encrypt or plain text?

if I get a private key form keystore file of `ciphertext` tag
it is a encrypt privateKey.
how do I unencrypt it
Thanks.

**Comment by a7ex12** [comment]
In this case use unencrypted private key in hex string format. You can get it by:
```
ECKey key = new ECKey();
String privKey = Hex.toHexString(key.getPrivKeyBytes());
```

or

you can get it from any word:
```
String privKey = Hex.toHexString(HashUtil.sha3("cow".getBytes()));
```

Or you may use byte[] private key format removing Hex.toHexString() and then you also shouldn't use Hex.decode(), for example:
```
byte[] senderPrivateKey = HashUtil.sha3("cow".getBytes());
```

**Comment by cheershendtco** [comment]
@a7ex12 
I just complete a transaction with SendTransaction.java
Thanks a lot !
really appreciate your time.

**Pull request merged**
