### PR TITLE
Code cleanups

### PR DESCRIPTION
**Pull request by loxal**
I’ve done several adjustments, mainly around code cleanup & clarification. 

HTH,
Alex

### CODE REVIEW

**Comment by Nashatyrev** [comment]
Hi @loxal, can you please do pull requests on stage?

**Comment by loxal** [comment]
@Nashatyrev yes, I’ll do. This one seems broke the CI anyway. However I run `./gradlew clean build` on `stage` and I get failing tests there:

org.ethereum.solidity.CompilerTest > simpleTest FAILED
    com.fasterxml.jackson.databind.JsonMappingException at CompilerTest.java:28

**Comment by Nashatyrev** [comment]
We will review our branches after upcoming release, but currently the `stage` is the working branch 
What OS are you working on?

**Comment by loxal** [comment]
I’m running the tests on a Mac.

**Comment by Nashatyrev** [comment]
Ok, cool, we have some issues with `solc`on Mac. Can you assist with fixing that?

**Comment by loxal** [comment]
Sure, I had also some issues using solc’s optimizations yesterday. If you’ve filed an issue already you can give me the issue number and I’ll give it a prio.

**Pull request closed without merging**
