### PR TITLE
fix #917 : fix bug in decodeBigInteger & refactor encodeElement

### LINKED ISSUE #917: decodeBigInteger doesn't work properly
Here's a test case:

```
    @Test
    public void encodeDecodeBigInteger() {

        BigInteger expected = new BigInteger("9650128800487972697726795438087510101805200020100629942070155319087371611597658887860952245483247188023303607186148645071838189546969115967896446355306572");
        byte[] encoded = encodeBigInteger(expected);
        BigInteger decoded = decodeBigInteger(encoded, 0);
        assertNotNull(decoded);
        assertEquals(expected, decoded);
    }
```

### PR DESCRIPTION
**Pull request by mlahia**

### CODE REVIEW

**Comment by Nashatyrev** [comment]
@mkalinin you may want to check this

**Comment by zilm13** [comment]
Should be resolved with #975

**Comment by mlahia** [comment]
@zilm13 and @bendyarm  : it would have been nice of you to put some explanation to why my proposed change is rejected. Thanks.

**Comment by zilm13** [comment]
@mlahia I've used part of your fix, sorry, just copied it, both were not complete, started from largest.
I've used your changes for encodeElement.

**Comment by mlahia** [comment]
@mlahia no problem, hope it helped !

**Comment by zilm13** [comment]
@mlahia Yeah, you helped. We are a bit constrained now because the library was without support for some time and we need to return fast to normal operation. I'd ask you for changes while not in rush.
Thank you.

**Pull request closed without merging**
