### PR TITLE
Web3

### PR DESCRIPTION
**Pull request by raltman**
Hi Roman,

Here is a first version a web3 implementation. It is still work in progress, but many methods are already implemented.

The most significant change we had to make was to add a store that works as a hashtable to be able to locate transactions easily by hash. It also stores the transaction receipt.

Looking forward to your thoughts!

Ruben

### CODE REVIEW

**Comment by oscarguindzberg** [comment]
There is a non-merged pull request you can try
https://github.com/ethereum/ethereumj/pull/352

**Comment by Nashatyrev** [comment]
Hi Ruben, 
we appreciate much your valuable PR especially taking into account we are going to add RPC support shortly. I'm planning to take the majority of your changes for this, but we are going to implement this as separate dependent project, outside of the core. 
Best regards,
Anton.

**Comment by raltman** [comment]
Hi Anton! Thanks for your reply! Is the branch you are working on public? There were some pending issues (filter-related methods, lookups on different heights of the blockchain, etc.) that we stil have to work on. 
If you are haven't worked on that, maybe we can help.
Thanks,
Ruben

**Comment by Nashatyrev** [comment]
Hi @raltman,
Just pushed the initial draft for JSON-RPC here: https://github.com/ethereum/ethereumj/tree/feature%2Fjson-rpc
Thanks to you PR - I've taken a lot of code from it. 
The implementation is not tested yet. 
BTW did you find any testing suite for JSON-RPC or/and Web3?
Thanks!

**Comment by gadhamvijaykumar** [comment]
Hi @Nashatyrev,
When are you planning on releasing JSON-RPC project?
Thank you,
Vijay

**Pull request closed without merging**
