### PR TITLE
Null hash for transaction, mainly with Standalone blockchain

### PR DESCRIPTION
**Pull request by ESchouten**
Fix for empty array returned when (hash == null && parsed == true && rlpEncoded != null). See pull request #1057

### CODE REVIEW

**Comment by zilm13** [comment]
@ESchouten could you, please, add a test which is failing in current develop, but will pass with your fix. I couldn't reproduce the same bug and have not find the place in code where it could happen. Looks like I'm missing something. 
Also such test could be helpful not to open this bug again in future.

**Comment by ESchouten** [comment]
@zilm13 I agree writing a unit test which demonstrates the race condition would be ideal. Problem is, I have not yet identified the source of this issue.
The error occurs while deploying a smart contract on the standalone blockchain on faster pc's and servers, while on slower servers and often in the IDE's debug mode it does not, making finding the source harder.
If it helps, we're using [https://github.com/adridadou/eth-propeller-ethj](eth-propeller)

**Comment by ESchouten** [comment]
I am however able to repoduce the state of where rlpEncoded is initialized and the hash byte array is empty, though when trying to debug the origin of this, the race condition does not occur, probably due to the IDE pausing threads etc.

The only code I could find initializing the rlpEncoded array and not setting the hash value is located in InternalTransaction.java, though the class' method does not seem to be called.

**Comment by zilm13** [comment]
@ESchouten so, it's race condition, in this case setting `getEncoded` to be `synchronized` makes more sense for me. What do you think?

**Comment by ESchouten** [comment]
Agree, seems to work aswell! Still, in that case we're assuming hash string is set when `rlpEncoded` is set and `parsed` is true, which works right now, but might not be very maintainable.

E.g. The class InternalTransaction extends Transaction and overrides `getEncoded` but doesn't set the hash value.

**Comment by zilm13** [comment]
@ESchouten why it's not maintainable?

`InternalTransaction` never goes out of VM

**Comment by ESchouten** [comment]
@zilm13 Ah that explains.

**Comment by ESchouten** [comment]
Reverted my change and made `getEncoded` synchronized to prevent the race condition, as you suggested.

**Pull request merged**
