### PR TITLE
Flexible new config subsystem

### PR DESCRIPTION
**Pull request by swaldman**
At some level, this goes under the heading of "very elaborate fixes of things not really broken", but I think that this is pretty good and worth considering. 

There are a lot of changes here. Please read the [README](https://github.com/swaldman/ethereumj/blob/4f97482b7030f25590a064bc20556a073302d70a/ethereumj-core/src/main/java/org/ethereum/config/README.md) I've placed in the config directory for a description and motivation.

Anyway, I hope it's not entirely useless!

(I'd be glad to try to help on more urgent protocol compliance stuff, but it's hard for me to figure out where to start...)

### CODE REVIEW

**Comment by romanman** [comment]
Hey  @swaldman : thanks it looks like good direction
I need some time to think on it.

**Comment by swaldman** [comment]
I'd imagine... ;)

**Comment by romanman** [comment]
@swaldman : what do you think on 
https://github.com/typesafehub/config

**Comment by swaldman** [comment]
i love and use it! (it's in the PR, which would have to be updated i think to track recent ethereumj versions.)

**Comment by romanman** [comment]
@swaldman : that is why I asking , cause I think the general direction
to the type of config you introduced is very good , and I want to adapt
it but there was ton of changes on the way so auto merge wont 
work , so I hope you wont mind that I will do it manually ?

**Comment by swaldman** [comment]
@romanman oh, feel free! do whatever is good, don't worry about me!

or if you'd like for me to bring this forward, i'd be glad to but i'd need a few days.

**Comment by romanman** [comment]
@swaldman : ok cool

**Pull request closed without merging**
