### PR TITLE
Feature/v64 draft

### PR DESCRIPTION
**Pull request by zilm13**
@Nashatyrev 
Not for merge. For review and discussion. DL part.
Here goes my issues with it:
1) parOffset is 33. Why? I don't know and whether it could be changed. ETH ends on 28
2) Often syncDone is not fired in SyncManager for a long time after unsecure sync
3) What validations I could add to this?
4) Is not final, I will run more chain validation tests

### CODE REVIEW

**Comment by Nashatyrev** [comment]
> parOffset is 33. Why? I don't know and whether it could be changed. ETH ends on 28

Probably left from the time when Warp was positioned as Eth64
> Often syncDone is not fired in SyncManager for a long time after unsecure sync

How many top blocks imported before `onSyncDone` fired?

**Comment by Nashatyrev** [comment]
> What validations I could add to this?

The best validation is that you finally get the right state root

**Comment by zilm13** [comment]
@Nashatyrev 
1) If so, did I correctly implement it? It could broke things if there will be, say [eth, par, shh]
2) From my observation it was not fired even after 10 minutes after reaching HEAD when there are 3 peers, and was fired when there are a lot of peers.

**Comment by Nashatyrev** [comment]
> If so, did I correctly implement it? 

Hope so :) 

2. We have an issue on this I couldn't reproduce: https://github.com/ethereum/ethereumj/issues/605
Can you please submit logs there when this happens?

**Pull request closed without merging**
