### PR TITLE
Update P2pHandler.java

### PR DESCRIPTION
**Pull request by Bitcoinzie**
Updated VERSION to 3 for p2pVersion message.

### CODE REVIEW

**Comment by romanman** [comment]
Hey @Bitcoinzie : it's more than version bumping 
at that stage , we are working on encrypted messages, 
asymetric security in handshake , and DHT.

**Comment by Bitcoinzie** [comment]
That's why i closed it..

**Comment by Bitcoinzie** [comment]
Further, I bumped the version on my end just to stop the damn thing from hanging.  I didn't notice I committed here until a couple hours later, that's when I closed this commit. my bad.. :)

**Comment by romanman** [comment]
sure, np.

**Pull request closed without merging**
